Future
AndreyOmel/ALG3Cource pull request #1
Opened 2024-10-28 15:37 UTC by AndreyOmel

Алгоритмы сортировки

2024-10-30 10:19 UTC, BalakinaEP requested changes

2024-10-30 10:19 UTC, BalakinaEP commented on sorting1909/Source.cpp
> +    int i, j;
неинициализированные переменные

2024-10-30 10:19 UTC, BalakinaEP commented on sorting1909/Source.cpp
> +    int i = low - 1;
size_t

2024-10-30 10:19 UTC, BalakinaEP commented on sorting1909/Source.cpp
> +    int i, j;
size_t

2024-10-30 10:19 UTC, BalakinaEP commented on sorting1909/Source.cpp
> +    for (int j = low; j < high; j++) {
size_t

2024-10-30 10:19 UTC, BalakinaEP commented on sorting1909/Source.cpp
> +    for (int i = 0; i < size-1; i++)
size_t

2024-11-07 12:50 UTC, BalakinaEP approved these changes

2024-11-07 12:51 UTC, BalakinaEP commented
Еще нужно считать количество операций и сравнить 3 алгоритма между собой

2024-11-27 16:41 UTC, AndreyOmel commented
Методы сортировки

2024-11-27 16:41 UTC, merged